- name: Deploy dynamic secrets
  uses: kornicameister/gh-secrets-action@master
  with:
    repository: kornicameister/gh-secrets-action
    token: ${{ secrets.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 }}
    secrets: |
      TINY_URL: q2aalnqpy4v5jhj6ld9m7zc2bninkerr8hms02u7s3a4awgr
