name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  my-job:
    runs-on: ubuntu-latest
    env:
      TINY_KEY: ${{ secrets.TINY_KEY }}
    steps:
      - name: My Step
        run: echo $TINY_KEY
